---
title: "p8105_hw6_tt2714"
author: "Tiffany Tu"
date: "11/19/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)
library(knitr)
library(MASS)
library(forcats)
library(broom)
```

## Problem 1
#### Data cleaning...
```{r message = FALSE, warning = FALSE}
homicide = read_csv(file = "./homicide-data.csv") 
homicide_citystate = homicide %>% 
  unite(city_state, c(city, state), sep = ", ", remove = T) %>% 
  filter(!grepl('Dallas|Phoenix|Kansas City|Tulsa', city_state)) %>% 
  mutate(disposition = ifelse(disposition == "Closed by arrest", 1, 0),
         victim_race = ifelse(victim_race == "White", 1, 0), 
         victim_sex = ifelse(victim_sex == "Male", 1, 0)) %>% 
  mutate(victim_age = as.numeric(victim_age), 
         victim_sex = as.factor(victim_sex), 
         victim_race = as.factor(victim_race),
         victim_race = fct_relevel(victim_race, "1"))
```

#### Logistic Regression Model for Baltimore, MD 
Outcome: disposition of homicide
Reference group: race
Predictors: sex and age    

Use `broom::tidy` to clean up the model and include odds ratio with confidence intervals. 
```{r}
baltimore = homicide_citystate %>% filter(city_state == "Baltimore, MD")
baltimore_glm = glm(disposition ~ victim_race + victim_age + victim_sex, 
                    data = baltimore, family = binomial())

baltimore_glm %>% 
  broom::tidy(., conf.int = TRUE) %>% 
  mutate(odds.ratio = exp(estimate),
         conf.low = exp(conf.low),
         conf.high = exp(conf.high)) %>% kable()
```



## Problem 2
```{r}
 
```
